#!/bin/bash
# Install Moltbook skill into OpenClaw workspace
# For RWO (ReadWriteOnce) PVCs - runs from inside the pod
#
# NOTE: setup-agents.sh runs this automatically.
#       Use this script only for manual re-installs.
#
# Reads OPENCLAW_NAMESPACE from .env (generated by setup.sh)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Parse flags
K8S_MODE=false
for arg in "$@"; do
  case "$arg" in
    --k8s) K8S_MODE=true ;;
  esac
done

if $K8S_MODE; then
  KUBECTL="kubectl"
else
  KUBECTL="oc"
fi

# Load .env
if [ -f "$REPO_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env"
  set +a
fi

if [ -z "${OPENCLAW_NAMESPACE:-}" ]; then
  echo "ERROR: OPENCLAW_NAMESPACE not set. Run setup.sh first or set it manually."
  exit 1
fi

echo "Installing Moltbook skill..."
echo "  Namespace: $OPENCLAW_NAMESPACE"
echo ""

# Deploy ConfigMap
echo "1. Deploying skill ConfigMap..."
$KUBECTL kustomize "$SCRIPT_DIR" \
  | sed "s/namespace: openclaw/namespace: $OPENCLAW_NAMESPACE/g" \
  | $KUBECTL apply -f -
echo ""

# Get running pod
echo "2. Finding OpenClaw pod..."
POD=$($KUBECTL get pods -n "$OPENCLAW_NAMESPACE" -l app=openclaw --field-selector=status.phase=Running -o jsonpath='{.items[0].metadata.name}')
if [ -z "$POD" ]; then
  echo "ERROR: No running OpenClaw pod found in $OPENCLAW_NAMESPACE"
  exit 1
fi
echo "   Found: $POD"
echo ""

# Copy skill to workspace
echo "3. Copying skill to OpenClaw skills directory..."
$KUBECTL get configmap moltbook-skill -n "$OPENCLAW_NAMESPACE" -o jsonpath='{.data.SKILL\.md}' | \
  $KUBECTL exec -i -n "$OPENCLAW_NAMESPACE" "$POD" -c gateway -- \
    sh -c 'mkdir -p /home/node/.openclaw/skills/moltbook && cat > /home/node/.openclaw/skills/moltbook/SKILL.md && chmod -R 775 /home/node/.openclaw/skills'
echo ""

# Verify
echo "4. Verifying installation..."
$KUBECTL exec -n "$OPENCLAW_NAMESPACE" "$POD" -c gateway -- ls -la /home/node/.openclaw/skills/moltbook/
FILE_SIZE=$($KUBECTL exec -n "$OPENCLAW_NAMESPACE" "$POD" -c gateway -- sh -c 'wc -c < /home/node/.openclaw/skills/moltbook/SKILL.md')
echo "   Skill file size: ${FILE_SIZE} bytes"
echo ""

echo "Moltbook skill installed successfully!"
echo "The skill is now available to all agents in OpenClaw."
