#!/bin/bash
# Remove custom agents from OpenClaw
# Keeps: Shadowman, secrets, Moltbook registrations (unless --unregister-from-moltbook)
# Removes: Agent cron jobs, workspace files, reverts config to shadowman-only
#
# Usage:
#   ./remove-custom-agents.sh                          # Remove from OpenClaw only
#   ./remove-custom-agents.sh --unregister-from-moltbook  # Also delete agents from Moltbook
#
# Reads OPENCLAW_NAMESPACE and OPENCLAW_PREFIX from .env (generated by setup.sh)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Parse flags
UNREGISTER_MOLTBOOK=false
for arg in "$@"; do
  case "$arg" in
    --unregister-from-moltbook) UNREGISTER_MOLTBOOK=true ;;
  esac
done

# Load config from .env
if [ -f "$REPO_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env"
  set +a
else
  echo "ERROR: No .env file found at $REPO_ROOT/.env"
  echo "Run setup.sh first, or set OPENCLAW_NAMESPACE and OPENCLAW_PREFIX manually."
  exit 1
fi

# Validate required vars
if [ -z "$OPENCLAW_NAMESPACE" ]; then
  echo "ERROR: OPENCLAW_NAMESPACE not set in .env"
  exit 1
fi

# Determine agent names (prefixed if OPENCLAW_PREFIX is set)
if [ -n "$OPENCLAW_PREFIX" ]; then
  PHILBOT_ID="${OPENCLAW_PREFIX}_philbot"
  RESOURCE_OPTIMIZER_ID="${OPENCLAW_PREFIX}_resource_optimizer"
  CRON_PHILBOT="${OPENCLAW_PREFIX}-philbot-daily"
  CRON_RESOURCE="${OPENCLAW_PREFIX}-resource-optimizer-scan"
else
  PHILBOT_ID="philbot"
  RESOURCE_OPTIMIZER_ID="resource_optimizer"
  CRON_PHILBOT="philbot-daily"
  CRON_RESOURCE="resource-optimizer-scan"
fi

# Also handle legacy agent names (from before prefix was enforced)
LEGACY_AGENTS=("audit_reporter" "mlops_monitor")
LEGACY_CRONS=("audit-reporter-scan" "mlops-monitor-check" "philbot-daily-post" "philbot-daily" "resource-optimizer-scan")

echo "Removing custom agents from OpenClaw..."
echo "  Namespace: $OPENCLAW_NAMESPACE"
if [ -n "$OPENCLAW_PREFIX" ]; then
  echo "  Prefix:    $OPENCLAW_PREFIX"
fi
echo ""

# Get running pod (exclude job pods)
echo "1. Finding OpenClaw deployment pod..."
POD=$(oc get pods -n "$OPENCLAW_NAMESPACE" -l app=openclaw --field-selector=status.phase=Running -o json | \
  jq -r '.items[] | select(.metadata.ownerReferences[0].kind=="ReplicaSet") | .metadata.name' | head -1)
if [ -z "$POD" ]; then
  echo "   WARNING: No OpenClaw deployment pod found — skipping cron/workspace cleanup"
  echo "   (Pod may not be running; config and restart will still be applied)"
  SKIP_POD=true
else
  echo "   Found: $POD"
  SKIP_POD=false
fi
echo ""

# Remove cron jobs
if [ "$SKIP_POD" = "false" ]; then
  echo "2. Removing cron jobs..."
  oc exec -n "$OPENCLAW_NAMESPACE" "$POD" -c gateway -- bash -c "
    cd /home/node
    for job in $CRON_PHILBOT $CRON_RESOURCE ${LEGACY_CRONS[*]}; do
      echo \"   - Deleting \$job...\"
      node /app/dist/index.js cron delete \"\$job\" 2>/dev/null || echo \"     (not found)\"
    done
  "
  echo "   Done"
  echo ""

  # Remove agent workspace directories
  echo "3. Removing agent workspace directories..."
  oc exec -n "$OPENCLAW_NAMESPACE" "$POD" -c gateway -- sh -c "
    for dir in \
      ~/.openclaw/workspace-${PHILBOT_ID} \
      ~/.openclaw/workspace-${RESOURCE_OPTIMIZER_ID} \
      ~/.openclaw/workspace-philbot \
      ~/.openclaw/workspace-resource-optimizer \
      ~/.openclaw/workspace-audit-reporter \
      ~/.openclaw/workspace-mlops-monitor; do
      if [ -d \"\$dir\" ]; then
        echo \"   - Removing \$(basename \$dir)...\"
        rm -rf \"\$dir\"
      fi
    done
  "
  echo "   Done"
  echo ""
else
  echo "2. Skipping cron job removal (no pod)"
  echo "3. Skipping workspace removal (no pod)"
  echo ""
fi

# Apply base config (shadowman only)
echo "4. Applying base config (shadowman only)..."
sed "s/namespace: openclaw/namespace: $OPENCLAW_NAMESPACE/g" "$SCRIPT_DIR/../base/openclaw-config-configmap.yaml" | oc apply -f -
echo "   Config updated to shadowman only"
echo ""

# Restart deployment
echo "5. Restarting OpenClaw deployment..."
oc rollout restart deployment/openclaw -n "$OPENCLAW_NAMESPACE"
echo "   Deployment restarting"
echo ""

# Optionally unregister from Moltbook
if [ "$UNREGISTER_MOLTBOOK" = "true" ]; then
  echo "6. Unregistering agents from Moltbook DB (direct PostgreSQL)..."

  # Build list of agent names to unregister
  AGENTS_TO_DELETE=("'$PHILBOT_ID'" "'$RESOURCE_OPTIMIZER_ID'")

  # Also try legacy names if different from current
  if [ -n "$OPENCLAW_PREFIX" ]; then
    AGENTS_TO_DELETE+=("'philbot'" "'resource_optimizer'")
  fi
  for legacy in "${LEGACY_AGENTS[@]}"; do
    AGENTS_TO_DELETE+=("'$legacy'")
  done

  # Join into SQL IN list
  SQL_IN_LIST=$(IFS=,; echo "${AGENTS_TO_DELETE[*]}")

  # Get PostgreSQL credentials from .env
  DB_USER="${POSTGRES_USER:-moltbook}"
  DB_NAME="${POSTGRES_DB:-moltbook}"

  # Find PostgreSQL pod
  PG_POD=$(oc get pods -n moltbook -l component=database -o jsonpath='{.items[0].metadata.name}' 2>/dev/null) || true

  if [ -z "$PG_POD" ]; then
    echo "   WARNING: PostgreSQL pod not found in moltbook namespace. Cannot unregister."
  else
    echo "   Using PostgreSQL pod: $PG_POD"
    echo "   Deleting agents: $SQL_IN_LIST"
    oc exec -n moltbook "$PG_POD" -- psql -U "$DB_USER" -d "$DB_NAME" -c \
      "DELETE FROM agents WHERE name IN ($SQL_IN_LIST);" \
      2>/dev/null || echo "   (failed — table may not exist or agents already removed)"
    echo "   Done"
  fi
  echo ""
fi

echo "Done!"
echo ""
echo "Remaining:"
echo "  - Shadowman agent (active)"
echo "  - Agent K8s secrets (kept for future use)"
if [ "$UNREGISTER_MOLTBOOK" = "true" ]; then
  echo "  - Moltbook registrations removed"
else
  echo "  - Moltbook registrations preserved (use --unregister-from-moltbook to remove)"
fi
echo ""
echo "Removed:"
echo "  - Agent workspace directories"
echo "  - Cron jobs"
echo "  - Config reverted to shadowman-only"
echo ""
echo "To re-add agents, re-run setup.sh"
