#!/bin/bash
# Setup RBAC for resource-optimizer agent
# Creates ServiceAccount + token, grants minimal read-only access to resource-demo namespace
#
# NOTE: setup-agents.sh runs this automatically.
#       Use this script only for manual setup or re-runs.
#
# Reads OPENCLAW_NAMESPACE and OPENCLAW_PREFIX from .env (generated by setup.sh)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Parse flags
K8S_MODE=false
for arg in "$@"; do
  case "$arg" in
    --k8s) K8S_MODE=true ;;
  esac
done

if $K8S_MODE; then
  KUBECTL="kubectl"
else
  KUBECTL="oc"
fi

# Load .env
if [ -f "$REPO_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env"
  set +a
fi

if [ -z "${OPENCLAW_NAMESPACE:-}" ] || [ -z "${OPENCLAW_PREFIX:-}" ]; then
  echo "ERROR: OPENCLAW_NAMESPACE and OPENCLAW_PREFIX must be set. Run setup.sh first."
  exit 1
fi

echo "Setting up RBAC for resource-optimizer agent..."
echo "  Namespace: $OPENCLAW_NAMESPACE"
echo ""

# Step 1: Apply RBAC resources
echo "1. Creating ServiceAccount and RBAC..."
$KUBECTL apply -f "$SCRIPT_DIR/resource-optimizer-rbac.yaml"
echo "   Done"
echo ""

# Step 2: Wait for token to be generated
echo "2. Waiting for ServiceAccount token..."
TOKEN=""
for i in $(seq 1 30); do
  TOKEN=$($KUBECTL get secret resource-optimizer-sa-token -n "$OPENCLAW_NAMESPACE" -o jsonpath='{.data.token}' 2>/dev/null | base64 -d) || true
  if [ -n "$TOKEN" ]; then
    echo "   Token generated"
    break
  fi
  echo "   Waiting... ($i/30)"
  sleep 2
done

if [ -z "$TOKEN" ]; then
  echo "ERROR: Token not generated after 60 seconds"
  exit 1
fi
echo ""

# Step 3: Find OpenClaw pod
echo "3. Finding OpenClaw pod..."
POD=$($KUBECTL get pods -n "$OPENCLAW_NAMESPACE" -l app=openclaw --field-selector=status.phase=Running -o jsonpath='{.items[0].metadata.name}')
if [ -z "$POD" ]; then
  echo "ERROR: No running OpenClaw pod found in $OPENCLAW_NAMESPACE"
  exit 1
fi
echo "   Found: $POD"
echo ""

# Step 4: Update .env file with token
echo "4. Adding OC_TOKEN to resource-optimizer .env..."
$KUBECTL exec -n "$OPENCLAW_NAMESPACE" "$POD" -c gateway -- sh -c "
  ENV_FILE=\$HOME/.openclaw/workspace-${OPENCLAW_PREFIX}_resource_optimizer/.env
  mkdir -p \$(dirname \$ENV_FILE)
  grep -v '^OC_TOKEN=' \$ENV_FILE > \$ENV_FILE.tmp 2>/dev/null || true
  mv \$ENV_FILE.tmp \$ENV_FILE 2>/dev/null || true
  echo 'OC_TOKEN=$TOKEN' >> \$ENV_FILE
"
echo "   Done"
echo ""

# Step 5: Verify permissions
echo "5. Verifying permissions..."
TEST_OUTPUT=$($KUBECTL exec -n "$OPENCLAW_NAMESPACE" "$POD" -c gateway -- sh -c "
  . \$HOME/.openclaw/workspace-${OPENCLAW_PREFIX}_resource_optimizer/.env
  curl -s -H \"Authorization: Bearer \$OC_TOKEN\" \
    --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
    https://kubernetes.default.svc/api/v1/namespaces/resource-demo/pods 2>&1 | head -20
" 2>&1) || true

if echo "$TEST_OUTPUT" | grep -q '"kind":"PodList"'; then
  echo "   Can read pods in resource-demo"
else
  echo "   WARNING: Permission check inconclusive — token may need time to propagate"
fi
echo ""

echo "RBAC setup complete!"
echo "  ServiceAccount: resource-optimizer-sa (in $OPENCLAW_NAMESPACE)"
echo "  Token: injected into workspace .env as OC_TOKEN"
echo "  Permissions: read-only access to resource-demo namespace"
echo ""
